#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

ENV_FILE="$ROOT/.env.local"

if [[ ! -f "$ENV_FILE" ]]; then
  CRON_SECRET="$(openssl rand -base64 32 | tr -d '\n')"
  WEBHOOK_SECRET="$(openssl rand -base64 32 | tr -d '\n')"
  GITHUB_TOKEN=""

  if command -v gh >/dev/null 2>&1; then
    GITHUB_TOKEN="$(gh auth token 2>/dev/null || true)"
  fi

  cat >"$ENV_FILE" <<EOF
# Generated by .cursor/setup-local.sh — do not commit
DIGEST_CHANNEL_ID=slack:C0BBBSHSLFQ
CRON_SECRET=${CRON_SECRET}
GITHUB_WEBHOOK_SECRET=${WEBHOOK_SECRET}
BOT_USER_NAME=repo-watch
NODE_ENV=development
EOF

  if [[ -n "$GITHUB_TOKEN" ]]; then
    echo "GITHUB_TOKEN=${GITHUB_TOKEN}" >>"$ENV_FILE"
  fi

  echo "Created .env.local"
else
  echo ".env.local already exists — leaving it unchanged"
fi

# Append optional secrets from the environment when missing locally
append_if_missing() {
  local key="$1"
  local value="${!key:-}"
  if [[ -n "$value" ]] && ! grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
    echo "${key}=${value}" >>"$ENV_FILE"
    echo "Added ${key} from environment"
  fi
}

for key in SLACK_BOT_TOKEN SLACK_SIGNING_SECRET AI_GATEWAY_API_KEY OPENAI_API_KEY ANTHROPIC_API_KEY REDIS_URL CONNECTOR_SLACK CONNECTOR_GITHUB; do
  append_if_missing "$key"
done

pnpm install

echo ""
echo "Setup complete."
echo "  Dev server:  pnpm dev"
echo "  Health:      curl http://localhost:3000/api/dev/status"
echo "  GitHub test: curl http://localhost:3000/api/dev/repos"
echo ""
echo "For full Slack + AI Q&A, add these to Cursor Cloud Agent secrets:"
echo "  SLACK_BOT_TOKEN, SLACK_SIGNING_SECRET, AI_GATEWAY_API_KEY"
